/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_image_descriptor (XDR *xdrs, image_descriptor *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->Size))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->Buffer, 4096))
		 return FALSE;
	return TRUE;
}
